const { onCall, HttpsError } = require("firebase-functions/v2/https");
const { defineSecret } = require("firebase-functions/params");
const { GoogleGenerativeAI } = require("@google/generative-ai");

// The API key is stored as a Firebase secret, NOT in source code.
// Set it once via: firebase functions:secrets:set GEMINI_API_KEY
const geminiApiKey = defineSecret("GEMINI_API_KEY");

/**
 * Cloud Function: generateQuiz
 *
 * Accepts extracted PDF text from the client and returns 10 MCQs
 * generated by the Gemini API. The API key never leaves the server.
 *
 * Input:  { text: string }     — the extracted PDF text
 * Output: { questions: [...] } — array of quiz question objects
 */
exports.generateQuiz = onCall(
  {
    secrets: [geminiApiKey],
    // Enforce authentication — only logged-in users can call this
    enforceAppCheck: false, // Enable when you add App Check
    timeoutSeconds: 120,
    memory: "256MiB",
  },
  async (request) => {
    // 1. Verify the caller is authenticated
    if (!request.auth) {
      throw new HttpsError(
        "unauthenticated",
        "You must be logged in to generate a quiz."
      );
    }

    // 2. Validate input
    const text = request.data.text;
    if (!text || typeof text !== "string" || text.trim().length < 50) {
      throw new HttpsError(
        "invalid-argument",
        "The extracted text is too short or missing."
      );
    }

    // 3. Rate limit: cap text length to prevent abuse (~ 100K chars ≈ 50 pages)
    const trimmedText = text.substring(0, 100000);

    // 4. Build the prompt (identical to the old client-side prompt)
    const prompt = `You are an expert educational quiz generator. Read the following text and generate exactly 10 multiple-choice questions (MCQs) based on the material.
Each question must have exactly 4 options. Mention the correct option index (0 to 3).

Return ONLY a JSON array, where each object looks exactly like this:
{
  "question": "The question text",
  "options": ["Option A", "Option B", "Option C", "Option D"],
  "correctIndex": 2
}

Text to analyze:
${trimmedText}`;

    // 5. Call Gemini
    try {
      const genAI = new GoogleGenerativeAI(geminiApiKey.value());
      const model = genAI.getGenerativeModel({
        model: "gemini-2.5-flash",
        generationConfig: {
          responseMimeType: "application/json",
        },
      });

      const result = await model.generateContent(prompt);
      const rawText = result.response.text();

      if (!rawText) {
        throw new HttpsError("internal", "Gemini returned an empty response.");
      }

      // 6. Parse response — handle markdown wrapping
      let jsonString = rawText;
      if (jsonString.startsWith("```json")) {
        jsonString = jsonString.split("```json")[1].split("```")[0].trim();
      } else if (jsonString.startsWith("```")) {
        jsonString = jsonString.split("```")[1].split("```")[0].trim();
      }

      const parsed = JSON.parse(jsonString);

      // Handle both array and { questions: [...] } formats
      let questions;
      if (Array.isArray(parsed)) {
        questions = parsed;
      } else if (parsed.questions && Array.isArray(parsed.questions)) {
        questions = parsed.questions;
      } else {
        throw new HttpsError(
          "internal",
          "Gemini returned an unexpected format."
        );
      }

      return { questions };
    } catch (error) {
      console.error("Gemini API error:", error);
      if (error instanceof HttpsError) throw error;
      throw new HttpsError(
        "internal",
        `Failed to generate quiz: ${error.message}`
      );
    }
  }
);
