// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJouToL68hXmQhb2e0ObEoNExZ8EeYNRY',
    appId: '1:115673374904:web:01708f1b3f60fc0135544d',
    messagingSenderId: '115673374904',
    projectId: 'focusmate-7a9c5',
    authDomain: 'focusmate-7a9c5.firebaseapp.com',
    storageBucket: 'focusmate-7a9c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoNhXqpmY4wUGQ-vyRvi1sK3UokgSpOb0',
    appId: '1:115673374904:android:3715a2ccbb955db735544d',
    messagingSenderId: '115673374904',
    projectId: 'focusmate-7a9c5',
    storageBucket: 'focusmate-7a9c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp4WQhdUA07T0GNMcifxjcVVjMGUjuAFk',
    appId: '1:115673374904:ios:c9490bed690f353a35544d',
    messagingSenderId: '115673374904',
    projectId: 'focusmate-7a9c5',
    storageBucket: 'focusmate-7a9c5.firebasestorage.app',
    iosBundleId: 'com.example.focusMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp4WQhdUA07T0GNMcifxjcVVjMGUjuAFk',
    appId: '1:115673374904:ios:c9490bed690f353a35544d',
    messagingSenderId: '115673374904',
    projectId: 'focusmate-7a9c5',
    storageBucket: 'focusmate-7a9c5.firebasestorage.app',
    iosBundleId: 'com.example.focusMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJouToL68hXmQhb2e0ObEoNExZ8EeYNRY',
    appId: '1:115673374904:web:8921329b1068816f35544d',
    messagingSenderId: '115673374904',
    projectId: 'focusmate-7a9c5',
    authDomain: 'focusmate-7a9c5.firebaseapp.com',
    storageBucket: 'focusmate-7a9c5.firebasestorage.app',
  );
}
