import 'package:flutter/material.dart';
<<<<<<< Updated upstream
import 'auth/auth_screen.dart'; // Make sure this path is correct
import 'package:firebase_core/firebase_core.dart'; // Added this
import 'firebase_options.dart'; // Added this (generated by FlutterFire)

// Dummy AppLockCenter Screen
class AppLockCenter extends StatelessWidget {
  final String userName;

  const AppLockCenter({super.key, required this.userName});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        title: const Text('App Lock Center'),
        backgroundColor: Colors.grey[900],
      ),
      body: Center(
        child: Text(
          'Welcome, $userName!',
          style: const TextStyle(color: Colors.white, fontSize: 22),
        ),
      ),
    );
  }
=======
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'package:focus_mate/firebase_options.dart';
import 'package:focus_mate/theme/light_theme.dart';
import 'package:focus_mate/theme/dark_theme.dart';
import 'package:focus_mate/core/auth_gate.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    }
  } catch (e, stacktrace) {
    debugPrint("Initialization failed: $e\n$stacktrace");
  }
  runApp(const ProviderScope(child: FocusMateApp()));
>>>>>>> Stashed changes
}

// --- MODIFIED main() FUNCTION ---
Future<void> main() async {
  // Ensure Flutter is initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Run your app
  runApp(const FocusMateApp());
}
// --- END OF MODIFICATIONS ---

class FocusMateApp extends StatefulWidget {
  const FocusMateApp({super.key});

  @override
  State<FocusMateApp> createState() => _FocusMateAppState();
}

class _FocusMateAppState extends State<FocusMateApp> {
  Widget _currentScreen = Container();

  @override
  void initState() {
    super.initState();
    _currentScreen = AuthScreen(onAuthComplete: _handleAuthComplete);
  }

  void _handleAuthComplete(UserRole role, dynamic userData) {
    // Navigate to AppLockCenter after login/signup
    setState(() {
      _currentScreen = AppLockCenter(userName: userData['name']);
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'FocusMate',
<<<<<<< Updated upstream
      theme: ThemeData.dark(useMaterial3: true),
      home: _currentScreen,
    );
  }
}
=======
      theme: lightTheme,
      darkTheme: darkTheme,
      themeMode: ThemeMode.system,
      home: const AuthGate(),
    );
  }
}
>>>>>>> Stashed changes
